name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install hatch
        run: pipx install hatch

      - name: Build
        run: |
          hatch build
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
